### PR TITLE
Apply black formatting to Python codebase

### PR DESCRIPTION
**Pull request by dhimmel**
work in progress

closes https://github.com/manubot/manubot/issues/152

### CODE REVIEW

**Comment by dhimmel** [comment]
@epogrebnyak what do you think about the diff? I question whether this really does anything valuable.

**Comment by epogrebnyak** [comment]
Perhaps it shows your codebase is already well-formatted. Also some people are real serious about ' vs " and black fixes that. 

Black is needed for new submissions, to fix things like trailing newlines quickly. The fact it does little for existing codebase is good!

**Comment by epogrebnyak** [comment]
Does `black --check .` apply to both travis and appv? What is planned next on this?

**Comment by dhimmel** [comment]
> Does `black --check .` apply to both travis and appv?

Currently this PR only adds it to Travis. It runs on all travis jobs currently, although perhaps ideally it would only run on a single travis job, because we really only need to check once whether the formatting is correct.

> What is planned next on this?

I'm debating what to do about the cases where it makes the code less readable. Mostly this happens with `pytest.mark.parametrize` decorators where each it's most clear when each test is on its own line. Also it doesn't combine `([])`:

> image

The question is how much time to spend fighting it, versus just letting it do want it wants and accepting the slightly worse formatting.

**Comment by dhimmel** [comment]
> The question is how much time to spend fighting it, versus just letting it do want it wants and accepting the slightly worse formatting.

I am started to realize that fighting black is futile. One must just accept what it demands and move on (:. @epogrebnyak I am okay with merging if you are. Will this mess you up on #147?

**Comment by epogrebnyak** [comment]
I think the idea of black is that you cannot fight it, it is opinionated by default. With autopep8 there are more options (like exclude some type of formatting error), but tuning is dufficult too. 

Do you want to include some standard command to format a single file or all files to make or similar tool?

**Comment by dhimmel** [comment]
```
Do you want to include some standard command to format a single file or all files to make or similar tool?
```

The command is straightforward to reformat everything: `black .` or a specific subset like `black conftest.py`. Perhaps I should add a note to the README to do this if black fails on CI.

**Comment by epogrebnyak** [comment]
The comnands look pretty straightforward, but the notecwill be useful to
anyone not familiar with black. Some 'Developper guidelines' section in
README will be greatly appreciated.

In there we can add comments about the commands for testing locally
(excluding some travis-specific tests).

ср, 6 нояб. 2019 г., 18:04 Daniel Himmelstein <notifications@github.com>:

**Comment by agitter** [comment]
Should we make a contributing file with this type of developer guidance?  Then [GitHub will link](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) to it from issues and we can link it from the main readme.

**Comment by dhimmel** [comment]
I opened https://github.com/manubot/manubot/pull/171 to add more developer commands to the readme.

I'm not sure "contributor guidelines" is the same thing as "development commands" but I'm open to moving stuff here if we see a benefit to that.

**Pull request merged**
