### PR TITLE
Support metadata.manubot-randomize-author-order

### PR DESCRIPTION
**Pull request by dhimmel**
refs https://github.com/manubot/manubot/issues/315

Enables setting the following in metadata.yaml:

```yaml
manubot-randomize-author-order: true
```

### CODE REVIEW

**Comment by dhimmel** [comment]
Doesn't include an [`--only-on-ci`](https://github.com/greenelab/deep-review/blob/44ff95a2756bd03a32c046eb8983ac9c4f223b0a/build/randomize-authors.py#L24-L28) option for the randomization. Not sure that is really important. @agitter do you agree?

**Comment by agitter** [comment]
I agree we can skip the `--only-on-ci` option.

Do we want to support a manual seed?  One workflow might be to randomize authors in the early stages of writing and then fix one final randomized order when the manuscript is submitted or published.

**Comment by dhimmel** [comment]
> Do we want to support a manual seed

added in https://github.com/manubot/manubot/pull/317/commits/62f786fa5f7ce321c41a4ec18304aff7e1833cd0 to allow setting `manubot-randomize-author-order-seed`.

**Review by agitter — APPROVED** [review]
It looks like the test failures are due to the known DOI issues.

**Pull request merged**
