### PR TITLE
Generate docs and deploy to gh-pages

### PR DESCRIPTION
**Pull request by dhimmel**
Closes https://github.com/manubot/manubot/issues/117

After merge, docs should be regenerated for each commit and deployed to gh-pages. Uses https://github.com/timothycrosley/portray

### CODE REVIEW

**Comment by dhimmel** [comment]
Auto-generated docs from https://github.com/manubot/manubot/pull/153/commits/adb24e9b59864c4a57b10456a8d054be70192ebb: 
[docs.zip](https://github.com/manubot/manubot/files/3726258/docs.zip). You can download and open directory via a webserver locally.

**Comment by dhimmel** [comment]
@vincerubinetti @agitter @epogrebnyak: possibly of interest.

**Comment by epogrebnyak** [comment]
Did you add `portray` to `requirements.txt` or `requirements-dev.txt`?

**Comment by epogrebnyak** [comment]
On a stand-alone run I'm getting 

```
(base) D:\github\manubot>portray in_browser
d:\anaconda3\lib\site-packages\portray\config.py:137: UserWarning: No D:\github\manubot\pyproject.toml config file found
  warnings.warn(f"No {location} config file found")
?[K?[?25hDone?[0m Copying source documentation to temporary compilation directory
?[K?[?25hModule not found: manubot.cite.citekeysing pdocs?[K
```

Should there appear some config after you merge this PR to master?

**Comment by epogrebnyak** [comment]
So what is the overall benefit of this solution towards #117? We either want to generate docs locally (fails for me now) or see the docs somewhere like readthedocs as html.

**Comment by epogrebnyak** [comment]
> Auto-generated docs from [adb24e9](https://github.com/manubot/manubot/commit/adb24e9b59864c4a57b10456a8d054be70192ebb):
> [docs.zip](https://github.com/manubot/manubot/files/3726258/docs.zip). You can download and open directory via a webserver locally.

Imo, just makes the build slightly longer. Zipped html not too useful for dev process.

**Comment by dhimmel** [comment]
> Imo, just makes the build slightly longer. Zipped html not too useful for dev process.

I created the zip manually and uploaded so PR viewers could see the resulting docs without having to run the command themselves.

> So what is the overall benefit of this solution towards #117? We either want to generate docs locally (fails for me now) or see the docs somewhere like readthedocs as html.

This PR both gives a way to generate docs locally and would make the docs from the latest `master` version available using GitHub Pages at https://manubot.github.io/manubot (although we could change this URL to something custom).

I tested the command used by CI locally:

https://github.com/manubot/manubot/blob/adb24e9b59864c4a57b10456a8d054be70192ebb/.travis.yml#L17

I did get the `No {location} config file found` warning but don't remember the `Module not found: manubot.cite.citekeysing pdocs?` message. Is that an error that prevents you from generating output docs?

Wait... [CI failed](https://travis-ci.com/manubot/manubot/jobs/245590423#L956) with a nonzero exit status:

```shell
$ portray as_html --overwrite --output_dir=docs
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/portray/config.py:137: UserWarning: No /home/travis/build/manubot/manubot/pyproject.toml config file found
  warnings.warn(f"No {location} config file found")
Done Copying source documentation to temporary compilation directory
Module not found: manubot.process.tests.test_bibliography
The command "portray as_html --overwrite --output_dir=docs" exited with 1.
```

So I will have to fix this.

**Comment by vincerubinetti** [comment]
This looks fine to me, but I don't think it closes #117. 

It's good to have the comments from the code automatically put into docs, but fully and appropriately documenting Manubot such that it is usable to the common person will require significantly more content than this provides.

**Comment by dhimmel** [comment]
> I don't think it closes #117

I agree that generating the docs automatically is just the beginning. Next we'll have the hard task of making sure all the docs are complete and in the right place. But let's handle that in separate issues, since reading through #117 seems that it's mostly about getting docs set up.

Probably we will want to test out the portray docs for a few weeks before announcing them officially.

**Comment by epogrebnyak** [comment]
> Probably we will want to test out the portray docs for a few weeks before announcing them officially.

So where are the docs? https://manubot.github.io/manubot does not have them yet. Is there a working command to generate docs locally?

I see two stages in the process now handled by portray:

- generate html from docstrings
- publish on github pages 

I can set up sphinx documentation in the `\docs` or `\documentation` folder if portray is not working as expected. sphinx uses .rst files that can contain both docstring-based documentation and own text. It is as friendly of a tool compared to portray, but manageable.

Something that really helps with managing the docs is set of commands, in style of make that one can use for various project chores. Cross-platform is [invoke](http://www.pyinvoke.org), we can add a file `invoke.py` to project root and use the benefit of user-defined commands like `inv black`, `inv docs`, `inv clean`, etc to manipulate the project.

**Comment by epogrebnyak** [comment]
Also maybe portray is good at publishing the html ouput to gh-pages - maybe can use that part of its functionality with sphynx.

**Comment by epogrebnyak** [comment]
```
portray as_html --overwrite --output_dir=docs
```

is a command to build documentation in docs folder, so that gh-pages can pick it up? But how doing that on travis commits the html files to original repo?

**Comment by epogrebnyak** [comment]
Now there are also 'best-practive' presets for Invoke, called [Invocations](https://invocations.readthedocs.io/en/latest/api/docs.html#invocations.docs.build). One of good uses for them is versioning of pytest calls - eg there can be a set of parameters for a local user. 

This probably is better judged when seen in action, also invoke/invokations are not constrained just to docs, they are project-wide management tasks, so I can demonstarte in a separate PR.

As for docs we need a decision on where to store 'source files' (*.rst) and output html files. The output should probably by in `/docs` folder, but this is by accident is also default folder for sphinx source files. maybe `/documentation` for the source files.

**Comment by dhimmel** [comment]
> So where are the docs? https://manubot.github.io/manubot does not have them yet.

That should happen once we merge this PR

> how doing that on travis commits the html files to original repo?

This part of the Travis config deploys the docs:

https://github.com/manubot/manubot/blob/5e5b1558913d836cbb44d3e09e46a61e6d121a68/.travis.yml#L29-L36

> As for docs we need a decision on where to store 'source files' (*.rst) and output html files.

Currently all the source for the docs are in the python module. I think this makes sense for now. If our needs change we can move reorganize or rename the `docs` folder, which is currently for output.

**Comment by epogrebnyak** [comment]
<https://manubot.github.io/manubot/reference/manubot/cite/csl_item>

Looks like at the very least we need to offset the markdown lists with a newline. 

To check understanding:
- I can see the Reference on the right is generated from the docstrings and Table of contents on the left is a README.md?
- deploy-docs.sh makes a commit to manubot/manubot repo? but it is not [in commit list](https://github.com/manubot/manubot/commits/master) - what is the trick?

**Comment by dhimmel** [comment]
> deploy-docs.sh makes a commit to manubot/manubot repo? but it is not in commit list - what is the trick?

It commits to the [`gh-pages` branch](https://github.com/manubot/manubot/commits/gh-pages) which has an entirely different history than `master`. Example commit at https://github.com/manubot/manubot/commit/4d0f02c26dcb7645b226cb408ae0829e43e3399d.

> Looks like at the very least we need to offset the markdown lists with a newline.

Yeah I haven't actually looked into how we should format the docs, but in general I'm in favor of using whatever syntax is most like markdown.

**Comment by epogrebnyak** [comment]
> It commits to the gh-pages branch which has an entirely different history than master

Ah, I see - I was confused in Settigns menu there was no longer `gh-branch` option by default (I think it was there before). The `gh-branch` option appears if you create a `gh-branch` branch on your own, then it is in the menu.

**Comment by agitter** [comment]
There are some formatting issues, like the list formatting @epogrebnyak noted, but auto-generated docs are definitely an improvement.  Should we link https://manubot.github.io/manubot from the readme now?

A few other formatting notes:
- Verbatim or code blocks https://manubot.github.io/manubot/reference/manubot/pandoc/util/#get_pandoc_info
- URLs https://manubot.github.io/manubot/reference/manubot/cite/arxiv/#get_arxiv_csl_item

**Pull request merged**
